---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goose
components:
  - ../../components/common
resources:
  # Flux-Kustomizations
  - ./n8n/ks.yaml
