---
apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync-secret"
type: Opaque
stringData:
  RESTIC_REPOSITORY: '${RESTIC_REPO}/${APP}'
  RESTIC_PASSWORD: '${RESTIC_PASSWORD}'
  AWS_ACCESS_KEY_ID: '${MINIO_ACCESS_KEY}'
  AWS_SECRET_ACCESS_KEY: '${MINIO_SECRET_KEY}'
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
# apiVersion: volsync.backube/v1alpha1
# kind: ReplicationSource
# metadata:
#   name: "${APP}"
# spec:
#   sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
#   trigger:
#     schedule: "0 * * * *"
#   restic:
#     copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
#     pruneIntervalDays: 7
#     repository: "${APP}-volsync-secret"
#     volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
#     cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-4Gi}"
#     cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
#     cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
#     storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
#     accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
#     moverSecurityContext:
#       runAsUser: 568
#       runAsGroup: 568
#       fsGroup: 568
#     retain:
#       hourly: 24
#       daily: 7
#       weekly: 5
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
# apiVersion: volsync.backube/v1alpha1
# kind: ReplicationDestination
# metadata:
#   name: "${APP}-dest"
# spec:
#   trigger:
#     manual: restore-once
#   restic:
#     repository: "${APP}-volsync-secret"
#     copyMethod: Snapshot # must be Snapshot
#     volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
#     cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
#     cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
#     cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-4Gi}"
#     storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
#     accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
#     capacity: "${VOLSYNC_CAPACITY}"
#     moverSecurityContext:
#       runAsUser: 568
#       runAsGroup: 568
#       fsGroup: 568
