apiVersion: v1
kind: Secret
metadata:
  name: baby-buddy-secret
  namespace: default
type: Opaque
stringData:
  PG_USERNAME: ENC[AES256_GCM,data:H+pxI40IABeS,iv:zowWRhed1gd0iSIvT9UMg/vmYBGksle3gwIfTYRnX4w=,tag:w3MSadp0+KJZifc672qfPw==,type:str]
  PG_PASSWORD: ENC[AES256_GCM,data:7vHaJrIs0I0rxzL0HXE=,iv:fWltMnTheftJqGi47eYUrEFRIHHvzPiTSVaIjIEVBQI=,tag:2jKbIuWDWsCZRG63IKghBw==,type:str]
sops:
  age:
    - recipient: age12wyktvsrgcq2ew20w4s9wj3zgculzg9ck3lr47nhzjrf3qku847qmufzte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraTFyZFcrVGE5N1lCWG5w
        eVRIUDNjaGQ0eDE1TXUrMEJwRk1TRGFRMFIwCk9lK05wc0hRMUFYZlZZN2RJaE50
        RjJ0aFdEWWswVm8wcEEzcXFhc1dlMGsKLS0tIHY4UXQwczFOR0dObWNsU09jb2o2
        cjd0NE44WnYwWmw3S1I5ZTlmTFpWQVkK+RS0AcUdy+bufEjPt98+LgIEiLLMBF3z
        WUftoThRD4R8FclclP2SoBPkbFdBusKZuDFLOGreT6BBowxMyGMBfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-20T15:07:15Z"
  mac: ENC[AES256_GCM,data:wY+WA8X/1w+N6ObDTDSHvN3s9XoXqGJ/Ly7JmuznDKJcHpmXIDnqDVns9xV2LSN8moWdLTqqmrLpbYOLvU/6jimRcYQhYbrDPYKTJ6Hz7bR9A7AzyKPl8UHZZaOVDKjeRmFe+i/Z3oFtgAq6X4G4OqiXxjcnNWzCuVhgj/L+cb4=,iv:ktRfPUrU0cimttwkc9jrFq6VzSh74kBssyr8/HIVgic=,tag:ixTgWWJHTnrPgzphukSg9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
