apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:sLsnZSjM95QWmINrIw==,iv:t/6dsnN6RdwI5vYAij+/QjtEUmY2qz3D51DDsAbJFlM=,tag:3n/5koujnZzTJKLsC3mSHA==,type:str]
  NAS_IP: ENC[AES256_GCM,data:u6kvxQ3Ys/l0KOgchD4=,iv:6J3rOQ7LbMBPd9H/d2XgtMpgQWM/XVJ2VGsaYYcOHyU=,tag:RhQhdQgaeUDEG313tHhv9w==,type:str]
  RESTIC_REPO: ENC[AES256_GCM,data:v5ql2bjP99SIDq9C1NeKo4vOc48+TnSEZMiTefDNBTpH3k3ildOgVg==,iv:DuTl80FCNKS1ssubgMPvrHxTrepIvBP8LpGzgn7kRPY=,tag:AXYtFYq0LygF0RdlIiwi+Q==,type:str]
  #ENC[AES256_GCM,data:Lv7wKMJno5bXqZme3PCuu3HG9MMBXrEMFaF3fW6h,iv:33Wn/LSn32tY/XlkJNph5tr69PdCU46GVzSFSC+YIkU=,tag:/UHZbDAjITpYmO+wh4yrqg==,type:comment]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:s+YTpGJekAfhAwP08CY=,iv:yHSxae/z4cauF3SXHboJ4yRFd4ohKMRkO4Jxxqc8h8w=,tag:LB4qi4tiwAQ+1///3cJSNA==,type:str]
  #ENC[AES256_GCM,data:Q5zZopMCDDYagWdyTwFci4CuVwHAT2JpZjed4P1qqNvVexPVnH9/5jo=,iv:530+PAxEgl/ZWwhFtUETBfBnDVdrOtC6MhVCY3psjcM=,tag:WP45EfAnGDqfTojpntffxA==,type:comment]
  #ENC[AES256_GCM,data:dnI5BjLuNouDjCu53sX/ABYDSetmbSITYxrskQbrqGSr1kj5S4DibpPwoxG20NxUzdI2ztm3lNxtc8Ub/tTzexTXF81feA==,iv:uT9/uHYpvJ3xpafvHFkReq5ETd186m119hqnFdNtVC4=,tag:EsoKnCOI3SljNwQ2PU/WOQ==,type:comment]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:se+Xdi8xkJEWDrjlp7NqVnHeA25z5nQVKrE=,iv:c0WkUzNhyZ3aW8YCPVF9ysbiDLpJBKkAPz9UmK3Owrg=,tag:qf+alDx9pWnM8ezU5wU5Jg==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:Tx41JqrarvtGHm6ELsXMxNGPjeYVv+Ef/6ydWI1XUHcuH8MNnUSmz1un3ZqHkRdkni8kekgkWfxZlEQfIjPqLw==,iv:uHtojmRsO3uP+EPp430pX9JhriTqOw61LK9Lo+BXZwk=,tag:eo+b6XrHEaK5EelxBVuaOA==,type:str]
  POSTGRES_IP: ENC[AES256_GCM,data:NFmxTVItWKHzQ1YV1O/a,iv:XY0vV2ApJaEV3r7Z/Y/xxxNpTcJvnbb35lePAXmeS/A=,tag:+NWGC7zXO+ggbn/kUU1sKQ==,type:str]
  SECRET_LAN_CIDR: ENC[AES256_GCM,data:EIlJ1ebYyZNJzojFkq1J,iv:OQQmTQEd+wzkA1pEzotcZr3IkhWX7fiNHyYqIxVbIEw=,tag:bmDxtWIdg5R8A9bEWniOrg==,type:str]
  DOWNLOADS_VPN_PORT: ENC[AES256_GCM,data:cLB3P54=,iv:6F0IyMKbB18hzBby5lXE9TDT3gB4gsNntsX78ffz6TU=,tag:om9+v8cn34xb1bjZCUNz0A==,type:str]
  JELLYFIN_IP: ENC[AES256_GCM,data:GtAjFnnen6fKI9aAs/GX,iv:m0B/72ZRlpW9TM/O+zPOkxxpGg66LVzVaHHoAa6nYBE=,tag:m0Pf2SNO2ogzc3tZuYSZDw==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:LHNQ7r8Jbw9ne7BYt//Vjvl19+K9NrIIClfeBe4sqxG6g7bg,iv:ri/TW0mMe3whkGpAb7L/hhdCYeqwwVMWufPVeWyQXMI=,tag:ZXCmZCoGpLzNK8TQDv8jsw==,type:str]
sops:
  age:
    - recipient: age12wyktvsrgcq2ew20w4s9wj3zgculzg9ck3lr47nhzjrf3qku847qmufzte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QlZpUFNQOHlMa0JpYjFv
        UzVCRGp0UU5zd1NJUjlkSS9mUytScnkvanlnCjg1VVpnUGZDMTRrQWFUWVZhSGFX
        dkdpeHpQTGRjeWk5b2EyNldPUVlpdFUKLS0tIENHckhhTFNEVlY0REFvNWoxM2Ra
        NThOU1JZNkFUMktuV2U1NXUwODFlTUUKULGtE/cDlZKnEI3Lyzv6apW96zMn72+c
        rU++CaKoB/z6mDSIFrGlZaJHLK+ZnQGpBp2pKdgOKgy8yC5zdJ+sDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T01:26:42Z"
  mac: ENC[AES256_GCM,data:gQt4eRcM+a82ra0Cr7i8DdKoBivyW91NUpFO0Z20eOzQBRKynX6P01jiELo/oS/b/L7QAeyu961VPj1965nDOidT2OTCkweu2lpN/j5lt6hWFPtzfupmUA6a/GPK/6wh5GVpPtAkkOy6Icin/rdFi2bXqOvNx01IF3LATV2kCCs=,iv:QynDydiQil+M/QuQViQ9w6KJQh+W7GA9N2Ckb+3jVjE=,tag:JdpL50WmzMIYP8NszUAWMQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
