apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qc+tOFdlXRV7rpAzTw==,iv:Hq+gy5o+1EXR9hqPdlRWr+9A6U1dlzb9m8JUrgFsWOI=,tag:4rvc4w4UbNQHHhoycZrfOA==,type:str]
sops:
  age:
    - recipient: age12wyktvsrgcq2ew20w4s9wj3zgculzg9ck3lr47nhzjrf3qku847qmufzte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU2VEY1dYaUJwSUNyUUQ2
        Q21pK0tXK0ovZHA3LzVZaFZwZUVrUFgwMm1vCmRTY2NBQ2tPc3V0V3ppbUFBS0pl
        OVA2ZisxOG5aalN4eEpzWWQzWnBOR0kKLS0tIEl6WXFRcjE4bEJSelJHd2FHTjNy
        MVFWRTlMcTdadnF4NVlsbklBMmRwK3MKHF0z34gvtsSPIoXECq71K+SPKJ1MKl/u
        j5re7RTy22ckmYlR+CV0EehTb3gQBWtDkhf0YMm3GEpYIidaEAcMrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T22:54:35Z"
  mac: ENC[AES256_GCM,data:HOpZ0EH0HRzds5MoMgYbWREkRLpM+V6n0zFdTI5ulyqUs1+egMzFEhv/urhd8YYQaA3xIInMF9Yj1coSHshFlpTsrapMaF/yU1qoSTbfv/8Yqc4ohh3jmLEbR6eFWy3wsOiFG56QbJszXioCfMi4tVQdOYH5DuieYk5WlV6IYOc=,iv:SMaa/nQHgJZzGq3yLy4fYgQuEbK/YHmGOH3a1CFO2NQ=,tag:jrQ4cFa6ihH+SSAi1wAzsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
