apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:rObtPKLIHMLQs+yY7Q==,iv:EB9dxnIDWJapLnel4PqMLqhkTpfjk9G7DFLg23wDGfI=,tag:0YKuNDa/sCx0SlJa2VxD0A==,type:str]
  NAS_IP: ENC[AES256_GCM,data:9sC9Nyo2vYAxqBYzuf4=,iv:YxRjFUJbXXrMHDgE/NAZBwaYONFBrc/WeGu+T93QCDk=,tag:SlduQ3gyhSzOTyd/mcXj2A==,type:str]
  RESTIC_REPO: ENC[AES256_GCM,data:ZGna/bVEnaOHBBnqMdong60ONrubVZWBkDpn4YzFz/hnRGlcuIlnvg==,iv:B7N/lMkAkbbq5PmQOP057j26kjwTZxjRGb0UZGBajEw=,tag:twm8hscYct5+8W1MTO47Vw==,type:str]
  #ENC[AES256_GCM,data:skWs7NEoaCqTkkxD+KIWztQHfyeoXufH6psf6VZ6,iv:C0rWT+imd+ZcshXMbuI39oW0DBKXnRaX8t1UfgfRWRs=,tag:Oz/WSs/9vvBGBWFNRoODXg==,type:comment]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:GoP4Wswk7bv7b6Xx8Zk=,iv:br38q42yoDEx22mW03RpKVG9hgNf0zDkoDq6BnjPNI8=,tag:Pz7AY7lapdcNXShThkFsrg==,type:str]
  #ENC[AES256_GCM,data:twr8hyHkSOxRknKP9JjhBcUEFPy3GLwz1QpU057QwxjLrysw5g2rfCk=,iv:+CVaU8+agl4MB/D/+0wIWbcYUvWb7jXTqOYLVVx3ReM=,tag:BvTlKqPkw4jQu98WR56itA==,type:comment]
  #ENC[AES256_GCM,data:EkroI54/VBbCeas7R4ZxmAUz7lwiGtZgwCnU6qhOK4ZNDiUHWo4L9JsUUDvDJEGEeFvMZLFt2arj7UfIm+gunEPmVr3DWw==,iv:oIx6BkjupcJtgazc5mYzXBk9F1NVef/k1FoCuRPxEQQ=,tag:POa5U2dlqgSHUGXWtoydag==,type:comment]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Us/Gdq8KePsmaPVa1DqOM/DOwg4=,iv:LGhNkkxRl2/p5HHbxdWRjbtqZH0BuK3/OsV1IOV0dS4=,tag:DmiURFqqvXjlE3AnM/2lxQ==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:3Jkm5wGa7tRrEozGnLTotmlg4KbaNaHBIkvA9WzjyrSUNTb85hqF9w==,iv:h//eMct40+hq8KKoz7JcCmUsqcrlmAvz78KipkEyAiU=,tag:1qNlF6PrsQRXi6PZjLFqdQ==,type:str]
  POSTGRES_IP: ENC[AES256_GCM,data:MwSFPdwWwgAMQMvanmUe,iv:AP4KIYsK+A5XuKcEZKecVC45fmeXHk56kxX7Ia/DN3U=,tag:LwyNmH8lmd8EsnGixro9Aw==,type:str]
  SECRET_LAN_CIDR: ENC[AES256_GCM,data:oOZ4rAtec6KmLoaWDVp/,iv:4SMZ+aU/Wg7Ykagh4DYdRnGR9c3Hiq1zXXk++N8PZ5s=,tag:fLslL+tS3DGrA4EVdWK4fA==,type:str]
  DOWNLOADS_VPN_PORT: ENC[AES256_GCM,data:fPUp7OI=,iv:wygyGtXg1jgc3Pkl0rYtWDJTFzjUBdD9b5L4sKp/Guc=,tag:et5Wgfaxn90VKMxhQk20Mw==,type:str]
  JELLYFIN_IP: ENC[AES256_GCM,data:W7i1+oRC+xRyz7pTHcIq,iv:DrygrynmZO+N+76i/m9OHGxObcQTLjEJh/mFqFSXIaQ=,tag:36MJUunSNOiS/wIgPv4ySg==,type:str]
sops:
  age:
    - recipient: age12wyktvsrgcq2ew20w4s9wj3zgculzg9ck3lr47nhzjrf3qku847qmufzte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZm05NlBnaHlLS09ORlBx
        Q3h3UkVhTndOQ2xxTmtVRVJCM1dMay9lY0VrCkp4R2xiWU13Mk5YQUZGeWdNQzFW
        aTlSamtaeWxqUTdDRENVcDFPZzVGNHcKLS0tIDhMUE1rd1pmN3V2c2lVTTM0U2Vo
        Y3czOFRJd05HbnQzN0JYTTREbERlbVkK4uF7yKksH1/P6Em4azmsoFBoAP0YEtvI
        UizAFHEbFf/oReupic6vWP3nMVNYFoMgRIRCytIpthSSWh1xxPVnDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-19T21:01:07Z"
  mac: ENC[AES256_GCM,data:S2YMWZGE/70Rh0u4g6LMFQOUMJ7cEkfOd8h10Wpf5Iylmw66vjJl/gm63adU1WQDUOWpi0bBLGahMIqgmmvycHsWvKDEQR6yn5Hkp0lfCfjZk8ei7RXlnXrMW7yvOvHDrTp+9pfz4Ut89CT9niSOuEnI3If9BY3hG1Gd/0+9HaM=,iv:YyrIPRPoQRgpTYl2vX3IlpTrELnQPmCxpPup7Tfg1Qc=,tag:X+vZTq0bo6Jg4O7tGZjZ5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
