apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:thaDQjO5AVi39aEPxA==,iv:HnTTfvq7SBhJsGVyh9idgdNQrTWrrXveFHAwcgaNKHg=,tag:ho7mqQXS1Z0xAx59lGLUIA==,type:str]
  NAS_IP: ENC[AES256_GCM,data:10RKHaD01sJyKCLswvE=,iv:95h9PNaiW2bmu3b3ToQh0FPtb7sXihOi4h4I7WbAuJw=,tag:BFrLKJxwhjNumF0yBS4+pw==,type:str]
  RESTIC_REPO: ENC[AES256_GCM,data:B+OP91SIzieP7lXh4825YD0rLi5DLgptFxBlAxpKN76TxkRyk31R+A==,iv:i5NzBOtMe8D/rb363qzulaptjBBOOL4AXDpUKfVSTng=,tag:e+TUzIrF+ZPvrTfdoH35cA==,type:str]
  #ENC[AES256_GCM,data:an7ng0DFzQ+OPm+rVxw8g09UDoGRB5oCmdmGkiHa,iv:wBgdmJMFdXP8KCtdrz8g1aKVqSOaxRDy20RfXdcg8wE=,tag:wdnFNJxvhX4Ya2qQpWAXzg==,type:comment]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:PIoHxHH+cvZRsD4lYWM=,iv:Cy6OF0wGEm/H9Lb40YYjJ63CPNNV02qfiOBOGxraKkE=,tag:8H6S5e++8K568JX/QbKokQ==,type:str]
  #ENC[AES256_GCM,data:UCtSrn0xaJgH1UqVttWCxspkJx+sRxEK3q2yyIulXPKrtclinHEeaks=,iv:QDtoAXgnenoYLnjOmG2GYyUMqbeZ9KLMqE6AgWCrJX4=,tag:KMQsnZui9KhI4RybTE//tg==,type:comment]
  #ENC[AES256_GCM,data:b4NLRtIr2vmCZgN7aLizHSITVz6sjJgyWJZFWSy3lriGtI5na1lX+V1RKcQmRwvfmTOgBklKOu5gdfV7uPVu+CDE4l+YNg==,iv:jSXvcUP3LS4uU1zSb3ZJ/pAKo2949rVo1ueOrZ0THv4=,tag:DMc87graVUW/9iMAzXVV+A==,type:comment]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:t98TXPa0R9l+xM5eJsyFmqokRrOvJa1ehg8=,iv:NMgOIeUdwa9ZbPYibctKMzO8ueCgdxxMEhRC79/enlE=,tag:iX1Zh9lH8d+NhorbhszUJw==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:tRU8KPtawoDagsrvkncn5RpIXA8Hefe0l0Z7/A1ZZWV1vZVBhQg4OFqGFRmkhPniKhnaL9YDOauHG7kL8OXicw==,iv:auaEwahwt0rD8ROgWMn4ZALBQlq4s9rLvGTLq812A7I=,tag:i2ga3Clxvt4TYOvbzBe7Iw==,type:str]
  POSTGRES_IP: ENC[AES256_GCM,data:hqE+UIBKxBH6NqqFfRhh,iv:wwDz26ol1x8mV1KeHeupFaviTxChUf1teFj5wOZ/V4A=,tag:hLMDfEdyZKNJQrWWgNR63A==,type:str]
  SECRET_LAN_CIDR: ENC[AES256_GCM,data:t9D2Zl3GSbswkg0jCLTP,iv:ehe995KAmbJU90t27j+0jc4ON2DYnAbSIP6vYZyimXg=,tag:H6JgUV3RieQsYuF0pOlCPQ==,type:str]
  DOWNLOADS_VPN_PORT: ENC[AES256_GCM,data:Ij/2X1I=,iv:TDvGu54QY07yYoho8lDMlk6G5J+s5U02uHAgPx0icfM=,tag:B8EJ4zeQlT0ix+tKLnhs0w==,type:str]
  JELLYFIN_IP: ENC[AES256_GCM,data:Vcqh8f16bg6PfsmKFqNG,iv:xCb4+pOQNecXaDQ35l7cbnqd6WEEQXllTmugmHx4B+c=,tag:YjohiU+bJJ4AE9dy+xbQVQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeXE2MWUvcUh2TFZTa3Zi
        UEIrZ21VTGhNcGd5QTNEV3ErWk9ZV0RiRVZRCnF2eXBuQlJ4c0tWTGVqNDlwTER1
        WFJsTVFzQXcyZjhBcTRpNUc2cHRCTDAKLS0tIDNFVDR6ejNXWDZXUU5NMFE0T3h6
        OEZWKzJVME5DbGp2bHpwRHZOTUhCdkUKb3omgb0j7ZMg+BRefsGqYLM7lD3DYx/P
        tw3pbvcB7ZOmYyNOC6rpg7RcDie8DWliQGE8lbYRMn1DT9cFxdjbfQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12wyktvsrgcq2ew20w4s9wj3zgculzg9ck3lr47nhzjrf3qku847qmufzte
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T18:17:32Z"
  mac: ENC[AES256_GCM,data:EGrip5Vns/35kz9KcJngN/V/gkjAsIOc1O2nDWfAoXAZQJxMwHKZUUv1LY5IhoqpFqkQjfe3Xo7KcjWktXBvLADYWL88eNs1yIe+7pClYLwJ1FlKcOTdpSmTlntve/K7ydsQ5PkbHjVn3ByX/dJGkVU5yZAfEr8Z/NjlQF1xwsI=,iv:Cv1t4Y9IrojDwIdWEoX7CRAkGhyNaPu9+qas4xaQXKA=,tag:LEnKZ+MVPwCJiARcHz3eDA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
