apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:I7gUObxUEnxQdhhI1g==,iv:RV4dUvymLpMppfOxiL85adqJkKhJ0wJNInApP5S6L8w=,tag:gEvKjAllGIfY47uKkMRvmw==,type:str]
  NAS_IP: ENC[AES256_GCM,data:ZLWL144RNUgkRYet3cg=,iv:cGdIKKn9kDACzwnx0IrAaCsuaBQ3z0+fw/U5TbjB5Ao=,tag:TeYmIkTfo1C4yc1A081NjA==,type:str]
  RESTIC_REPO: ENC[AES256_GCM,data:VX6cfhoOp907e6yJ2S0DTBYPuYM/CTrlZbnxDcE+Karji4IQRoEpLA==,iv:TFQ1/FOvBJNllrEkz9TrmwswlkwJt0CJM6Sf5V1suq0=,tag:N6fxNQx7cF0okBy+8cZ/yA==,type:str]
  #ENC[AES256_GCM,data:Aji135Tp/4ajw1jFh6bmknmhQaFflguNWZzP4VzZ,iv:YQOAKi9TcvKcccg4vJfRVjdsbU7S/N6MHrMLLjI7NfY=,tag:y4vd9QzUZqhgKl8COPgXcw==,type:comment]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:IsmRftcughye8/cxZqo=,iv:9zKXi2o9scsbtF90Ww9IIlOjjyfBtNwvoYZNRUPbS7o=,tag:1I+1rZ2ldVsfM10lgpZBlA==,type:str]
  #ENC[AES256_GCM,data:DIGrGwNfC0S23SPyE5YuhB7mqJFYAhYo/8Y98EXpOkE1NUP710V5nyo=,iv:ek5ycJ2N2t1OQqM6oktojUHVVMLI7lXWDciLdlgqO08=,tag:9EuNhGwagwK9YIKQ9nPy2g==,type:comment]
  #ENC[AES256_GCM,data:QCH9h55ObOD1W9u+FZX1w6aJvMZs3ePypcF0daRf/ELYGUYaCeyS6bZBo2/RvSbQZsE/zuFMoe2inTfb6t6XyHHaX5/vXQ==,iv:YRyN7k9TW++6xKKpq+H4UH2Mb2+mKZIVvl0iSTBfh+k=,tag:u5V8q4L7INpHbmiWq8bgPQ==,type:comment]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:P512wYZnPGG2nwxY58MX1KUG4Ug=,iv:j6V24nnS+Qu+dPQ+i9wByxwDkirhttSWfQDyoCE8Irs=,tag:TO5oI7C5+3cVP/feJ6h82w==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:B7ZPHkM2ModKL99RiYwgXJ7tyCjT8h35fWmq/XCnqOuQwwhag7Wu8g==,iv:1sPnRtd9nzydJQE1Ecpt/F0SCkudsVDgwUUikfp1k/c=,tag:xckZmEAQUvMvmgQN163CWQ==,type:str]
  POSTGRES_IP: ENC[AES256_GCM,data:3/ROwEXps8+Sp76hLG+m,iv:+9l4lr6OhfJhUavunqcvE6IQEp6ugEVEOS31OgIaL44=,tag:12KXlzVsvqB8XwGHZjMyng==,type:str]
  SECRET_LAN_CIDR: ENC[AES256_GCM,data:EtmCwpVsjXvAyurWzLE6,iv:R0gJrdh+eUTydzcUTp88eplFfqRvVE291R/oDfdqel4=,tag:hOcq06RCzVgauw+BLY/LhQ==,type:str]
  DOWNLOADS_VPN_PORT: ENC[AES256_GCM,data:LMU8Rjo=,iv:6FeqT67OwpgZ5A1xpHX42McAPCw/HXocC67EmMZj7Wc=,tag:mrFzANhD6KK/md4utmvN0g==,type:str]
  JELLYFIN_IP: ENC[AES256_GCM,data:yzdcsGTSkGBgNjphnF99,iv:Yb7MQY/ouZIos3IyyXk8DbVXdeskjdrOgUE1kz7Je58=,tag:2F6TK9d+tfIo5QUJdH+e7Q==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:X208N08bOthIJ2HIEkO0xpGuqr+gv/gbm6XnaCq9HRROVwne,iv:IkfUhjbvIevC4rMODuD4J8zqM1oZgCz/DWJwMKl3isI=,tag:uX3h3BSby/os0x5T0+r2Pw==,type:str]
sops:
  age:
    - recipient: age12wyktvsrgcq2ew20w4s9wj3zgculzg9ck3lr47nhzjrf3qku847qmufzte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU0NMYVFWTVJYS1JkMXR4
        aldPV3FsQnY1QWpLaDVaelAxQVN2amFMS1dFCjFDU2NFZTAwSUxHR2xxSG83REpH
        UWgyNWFNNzIySHhGVkdCNWZPUm92aFUKLS0tIG9IdEFyZkFlaENscDZaSkxRMisy
        QkVCWHlpdjlPVFBlRDFsL3JZdmxORjQKkxMMG5WvTwoMti87SS3vJT1oLg1C32gz
        RxIk9R9Fiff4MPyvH+os0AB8Tu4dYB6oWFSFhZxYEvVmSxGmrb++Qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-20T01:23:20Z"
  mac: ENC[AES256_GCM,data:6J9ECJDIgowWmg66etp1v1XbB316R4/eR1cahop5/ITpDdKYh4ZIYsN6vDrQnNSkyAtLPtXQ/MY4/YB6QOL79thq4Nm6mSpsTlTY4fyLTcV6cNQQLhgLPDSQwstfiNQfX48v3YSCMew9r8LmQJGXnzGOUpTpKF5k/ibJKuIYMrk=,iv:RW8Fi8COM+BsXDzGBXQ35D67qKrArM5IZcaOjOJR10M=,tag:jFjPoo8Tqx2gkfXDwYwuKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
