apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:08a2qkrGFks=,iv:GANV05jR1XpmI8O0m3oAeVJlosss+WOGTBie88bzphg=,tag:fHxOeHPp/7biEL5TkoQXHw==,type:str]
  password: ENC[AES256_GCM,data:xmaMmhp8jnnvN0duV/g=,iv:seJ0BQqep2M3e6z21Prn8Qp7fkVWqzFkmASns7rIrhA=,tag:owI8QrzZbToGYSW7w0zmSQ==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:w9X4JsCX5rfMLbSAHtsBy/sR9kU=,iv:2IcleK9DaIYnw6Mxj9ULgFVy4cIdE9kjXVwF9mQRPC0=,tag:T+9qC4OnruBymAMi9pcLeg==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:9ue5eRS8uvofByi3wMMrpRFL8kGKWBXJrFmWEFoGxhcU+mlqg/YVVw==,iv:pbAQ48ojdNjJ8uWadKzal8Y8hVoDHb9GOaG/9RTW3Mk=,tag:w30OjXqzClaJGCBp30q4YQ==,type:str]
sops:
  age:
    - recipient: age12wyktvsrgcq2ew20w4s9wj3zgculzg9ck3lr47nhzjrf3qku847qmufzte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQi94cjBvSWhBSkU0Zzk0
        dmZISnBOOGo4bnZkLzNIK2ptVTQ4ZTRsNWc0CjdqblJXbmZvUWppb2pZV2s2WS9j
        MmVKSnExM3MvbDZ3R3FXeFF2R0x2dmMKLS0tIE9CeXRNaWlYRkJPaTUzS3lhSTJT
        Ymk1REZoZUJHZldPV1ZhU1RGZ0xKSW8Kz5u2TLABaUPf7HGi282i6sNk79NJKd54
        0XWikMVQSyAfFE1Sg38N2DBTarj0sb1517rjifeaSCvKHPzID9WC7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-19T21:01:07Z"
  mac: ENC[AES256_GCM,data:wJX71G6ZjuRwq9rAhDmPMbmuCLATcw6aBy667lHUPERmLKJ2AnwMDU7e7Nl7BiTK83jeVDEwJO6RmIvQ74L4In/T66A8LCOOFBhJrK9ka72aYPVcNsdMwl6HeW73p54MWYQYwrWoqnjAr3iCb20GarRV8/qDVbVE5PCwQB+LsTQ=,iv:owVIxn982BZr0i9Wqudxn7O9HxT1d6TunlI0EA1UWgM=,tag:8LKEVCdWeaHRnKsvZ/xeQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
