apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:DlNGUAeqnCs=,iv:u32NdF0MN/yBd/I6ExGwODJB1YkDA+WOceTI00UY+XE=,tag:BWAQPHpPmMuWyrZoodq3Dg==,type:str]
  password: ENC[AES256_GCM,data:N8DaffKHiNBzs6KGQUo=,iv:B9E7k5Kid2YOf+XqGrSxymj5ZdL8P4csx5fsChyVs/I=,tag:lguRj2yr61Bi/xNB51ZjKg==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:71jkmLlZn3HXiNt62rSNuBD5tIi3fIpzo7M=,iv:eckdZhXafxE7at/PJEzAytfcjkhPd3cgMIuMyWswqnE=,tag:suHoQcrnMuzb8gBxWoRQdA==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:ulCJGXEGEHyzZz926WXJu8QkJuWq3k5GEi94grzxNphtTWlY/hS/1lHnp135Gpn0vXGAYH/tHaDp83qgqwL/IA==,iv:wP2cNwPeo7z9vqQQeFKrzGNt3a58d8BJ8P3hVlXNvV8=,tag:+H5VmJlsWgk9vKqiDOI3xA==,type:str]
sops:
  age:
    - recipient: age12wyktvsrgcq2ew20w4s9wj3zgculzg9ck3lr47nhzjrf3qku847qmufzte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRUhXWUxVZnNRWERMK3Uy
        M1JlU0FnczE5dTBrbjV6Z2F2N3FDcDEvTTJzCjRFUlJGUkg1UGY4VVh0amlzT2NX
        WkF5S1RITElZZk5KRjdqbTk0MGk1OWcKLS0tIFBORWhQMHJtYzFUWm5ISGt1L3Bs
        bHZMbnlHN3BuMHhmbkErTWdjQ2hxcmMKGwTBOxd83dUQaCIX5rK8c8J5836Q2+gu
        w/KhDXPX2ELiWmb9R77O6T2fYSZjcutACY6T1ibin5g6iX48YXhsog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T01:26:42Z"
  mac: ENC[AES256_GCM,data:30/7u9fZP00qYr0UAx6K4oRz5+A0yW/DBSJHDrKtvXI2GNnejA5f8RyWOPpx0ZPEiblQjL/sbvR8ImoyROIMzyBzI5C7/otFRzYCQpcnuisZyiTiNtEKzjqlAzVJDmsRCw1GglfI5lumm4l3y23yHDgSClrDxZ8hoJIsnjkXc9I=,iv:wzyGDWz7Udo1hnJVgmKYS5C4GkoFt46W+a3/tW0gi9s=,tag:u4vqJWNmObrACuHT9qBmGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
