---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname jellyfin
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: intel-device-plugin-gpu
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/media/jellyfin/app
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CAPACITY: 15Gi
      VOLSYNC_CLAIM: jellyfin
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
